const bandPhrases = [
  "The Electric Vibes", "Midnight Howlers", "Crimson Echo", "Sonic Pulse",
  "Velvet Storm", "Neon Mirage", "The Roaring Shadows", "Aurora Beats"
];

function generateName() {
  const city = document.getElementById("cityInput").value.trim();
  const pet = document.getElementById("petInput").value.trim();

  if (city && pet) {
    document.getElementById("result").innerText = `🎤 ${city} ${pet}`;
  } else {
    document.getElementById("result").innerText = "Please enter both your city and pet name!";
  }
}

function generateRandomName() {
  const random = bandPhrases[Math.floor(Math.random() * bandPhrases.length)];
  document.getElementById("result").innerText = `🎵 ${random}`;
}

function copyName() {
  const text = document.getElementById("result").innerText;
  navigator.clipboard.writeText(text);
  alert("Band name copied to clipboard!");
}

function shareName() {
  const text = document.getElementById("result").innerText;
  const url = encodeURIComponent(window.location.href);
  const msg = encodeURIComponent(text + " - Generated by Band Name Generator");
  const shareURL = `https://wa.me/?text=${msg}`;
  window.open(shareURL, "_blank");
}

function downloadName() {
  html2canvas(document.getElementById("resultCard")).then(canvas => {
    const link = document.createElement('a');
    link.download = 'band_name.png';
    link.href = canvas.toDataURL();
    link.click();
  });
}

function toggleTheme() {
  document.body.classList.toggle("dark");
}

